name: Run Selenium Tests

on: [push, pull_request]  # Se ejecutará en cada push o pull request

jobs:
  test:
    runs-on: ubuntu-latest  # Usaremos una máquina virtual con Ubuntu
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Descarga el código del repo

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Asegúrate de que sea compatible con Selenium

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Instala dependencias (si tienes este archivo)

      - name: Run Selenium Tests
        run: python SauceDemoHome.py  # Cambia por el nombre correcto de tu script
